name: C/C++ CI

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: MSBuild
      working-directory: dummy
      run: msbuild dummy.vcxproj /p:Configuration=Release /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m
    - uses: actions/upload-artifact@v1
      with:
        name: HWID Spoofer
        path: dummy/output/x64/Release/dummy
